server:
  port: 1234
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway: 
      routes: 
        - id: demo-service
          uri: lb://DEMO-SERVICE
          predicates:
            - Path=/demo/**
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
       